#For creating server

AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instance using CloudFormation
Parameters:
 InstanceType:
   Type: String
   Default: t2.micro
   AllowedValues:
     - t2.micro
     - t3.micro
   Description: EC2 instance type
 KeyName:
   Type: AWS::EC2::KeyPair::KeyName
   Description: Name of existing EC2 KeyPair
 VpcId:
   Type: AWS::EC2::VPC::Id
   Description: VPC Id
 SubnetId:
   Type: AWS::EC2::Subnet::Id
   Description: Subnet Id
Resources:
 EC2SecurityGroup:
   Type: AWS::EC2::SecurityGroup
   Properties:
     GroupDescription: Allow SSH and HTTP
     VpcId: !Ref VpcId
     SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: 22
         ToPort: 22
         CidrIp: 0.0.0.0/0
       - IpProtocol: tcp
         FromPort: 80
         ToPort: 80
         CidrIp: 0.0.0.0/0
 EC2Instance:
   Type: AWS::EC2::Instance
   Properties:
     ImageId: ami-051a31ab2f4d498f5 
     InstanceType: !Ref InstanceType
     KeyName: !Ref KeyName
     SubnetId: !Ref SubnetId
     SecurityGroupIds:
       - !Ref EC2SecurityGroup
     Tags:
       - Key: Name
         Value: GitHub-Actions-Server
Outputs:
 InstanceId:
   Value: !Ref EC2Instance
 PublicIP:
   Value: !GetAtt EC2Instance.PublicIp
